#!/bin/bash

# Automounter for removable media
udiskie &

# Wallpaper Backend
swww-daemon --format xrgb &

# Pyprland Daemon
pypr --debug /tmp/pypr.log &

# Bar
waybar &

kdeconnect-indicator &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Notify about devices connecting and disconnecting

# Idle daemon to screen lock
hypridle &

# Clipboard
wl-paste --watch cliphist store &

# Polkit authentication
/usr/libexec/polkit-mate-authentication-agent-1 &

# Screen sharing and portals
"$HOME"/.config/hypr/scripts/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord

# Audio
# easyeffects --gapplication-service &
nm-applet &
libinput-gestures &

EMOJI_FONT="Twemoji" vicinae server &
