#!/bin/bash

if [ -z "$1" ]; then
  exit 1
fi

program="$1"

if ! command -v "$program" >/dev/null 2>&1; then
  notify-send "Program not found" "Make sure you have installed $program"
  exit 1
else
  # if $2 is --flag-standalone, then run the program without any arguments
  if [ "$2" == "--flag-standalone" ]; then
    exec $program >/dev/null 2>&1 &
    exit 0
  fi
  exec $program "$2" >/dev/null 2>&1 &
fi
